### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by IBinary6** [hayasec/360SafeBrowsergetpass#1]
不是那么简单的,替换了ID是能解开数据库了.还有第二层加密你要解开.第三层混淆你要解开.

**Comment by hayasec** [comment]
建议您先用一下，附上截图。

**Comment by Gs52jrfnxnPXBGAW** [comment]
你好 我想问下有具体的解密算法吗

**Comment by hayasec** [comment]
1. 算法参考这位大哥的：[http://www.liulanqicode.com/360assis2.htm](http://www.liulanqicode.com/360assis2.htm)， 我目前不知道具体的加密细节，只是通过获取Browserview需要的值来进行离线解密，解决目前攻防演练中360安全浏览器没有命令行解密工具的问题。
2. 至于第一位师傅所说的加密算法，和 [http://www.liulanqicode.com/360assis2.htm](http://www.liulanqicode.com/360assis2.htm)提到的加密方式类似，如果师傅可以解出来并写一个开源工具方便大家自然是最好的。
