### ISSUE TITLE
关于sqlite3.dll

### ISSUE THREAD

**Issue by Vxer-Lee** [hayasec/360SafeBrowsergetpass#2]
LZ有sqlite3.dll的源码吗？
想具体看一下sqlite3_key的实现原理，官网的sqlite开源代码中并没有sqlite3_key这个函数，搜了下好像说收费版有。
然后网上的其他版本 SQLCipher 这个的sqlite3_key和LZ的好像不太一样，cipher的需要循环次数pbkdf，而LZ这个似乎没有传入过多参数，还有一个wxSqlite3这个我看了好像也对不上。或者LZ的sqlite3.dll下载地址来源能给一个吗？谢了

**Comment by hayasec** [comment]
我参考的是这个项目：https://github.com/rindeal/SQLite3-Encryption

**Comment by Vxer-Lee** [comment]
> 我参考的是这个项目：https://github.com/rindeal/SQLite3-Encryption

哈哈原来如此，昨天我差不多把所有sqlite加密的都找过了
SQLCipher
SEE
SQLiteCrypt
SQLiteEncrypt
WxSQLite
我看SQLiteEncrypt比较老，觉得可能不会是这个。

**Comment by Vxer-Lee** [comment]
要专门创个群 交流逆向吗？我也在弄取证.
