### ISSUE TITLE
程序有Bug

### ISSUE THREAD

**Issue by Vxer-Lee** [hayasec/360SafeBrowsergetpass#3]
`(51637587F6BB463a92D17DD7903A1F6F)VrKqbejDEDzuHB/xvbseUCKB08H0FaBt1UkraRnv4evJmsBhokroJytFrfX5E7jGqmKpKnpboRzs6EhMVmrBMypsqivrLZxCwvvM013s6zw=`
好像是登录账号同步过来的数据就是上面这样的。
实际测试中我的数据是这样的，而并非`(4B01F200ED01)xxxxxxxxx=` 
用lz代码并不能正常解密出来。

**Comment by hayasec** [comment]
对于登陆了用户中心的情况目前还在研究中，具体请看README。

**Comment by Vxer-Lee** [comment]
> 对于登陆了用户中心的情况目前还在研究中，具体请看README。

nice 我搞定了 他又套了一层aes 密钥应该是固定的 ，自己跟一下。

**Comment by hayasec** [comment]
后面一层我们这边目前遇到的问题是每个主机都不一样，本机密钥确实可以逆出来，这个问题您遇到了吗？

**Comment by Vxer-Lee** [comment]
> 后面一层我们这边目前遇到的问题是每个主机都不一样，本机密钥确实可以逆出来，这个问题您遇到了吗？

应该是固定的吧？我还没仔细测过，如果确定不一样的话应该是和uid拼接生成的，具体的话估计得看堆栈在生成密钥前追溯了.这部分应该不会太难

**Comment by Vxer-Lee** [comment]
> 后面一层我们这边目前遇到的问题是每个主机都不一样，本机密钥确实可以逆出来，这个问题您遇到了吗？

应该是固定的吧？我还没仔细测过，如果确定不一样的话应该是和uid拼接生成的，具体的话估计得看堆栈在生成密钥前追溯了.这部分应该不会太难

**Comment by Vxer-Lee** [comment]
我把搜狗的逆出来了....登录了用户中心的。
